In [10]:
import pandas as pd
distance = [120, 22, 2125, 271, 121, 523, 137, 237, 61, 145, 41, 12]
bins = [0, 25, 75, 200, 500]
category = pd.cut(distance, bins)
print(category)

[(75.0, 200.0], (0.0, 25.0], NaN, (200.0, 500.0], (75.0, 200.0], ..., (200, 500], (25, 75], (75, 200], (25, 75], (0, 25]]
Length: 12
Categories (4, interval[int64, right]): [(0, 25] < (25, 75] < (75, 200] < (200, 500]]

In [11]:
pd.value_counts(category)

/tmp/ipykernel_589/2654243906.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(75, 200]     4
(0, 25]       2
(25, 75]      2
(200, 500]    2
Name: count, dtype: int64

In [12]:
bin_names = ['Very Short Drive', 'Short Drive', 'Long Drive', 'Very Long Drive']
pd.cut(distance, bins, labels=bin_names)
pd.value_counts(pd.cut(distance,bins,labels=bin_names))

/tmp/ipykernel_589/3927492893.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.cut(distance,bins,labels=bin_names))

Long Drive          4
Very Short Drive    2
Short Drive         2
Very Long Drive     2
Name: count, dtype: int64

In [13]:
import numpy as np
pd.cut(np.random.rand(50), 10, precision=4)

[(0.007656, 0.1075], (0.007656, 0.1075], (0.4043, 0.5032], (0.007656, 0.1075], (0.2065, 0.3054], ..., (0.4043, 0.5032], (0.2065, 0.3054], (0.3054, 0.4043], (0.2065, 0.3054], (0.7999, 0.8988]]
Length: 50
Categories (10, interval[float64, right]): [(0.007656, 0.1075] < (0.1075, 0.2065] < (0.2065, 0.3054] <
                                            (0.3054, 0.4043] ... (0.6021, 0.701] < (0.701, 0.7999] <
                                            (0.7999, 0.8988] < (0.8988, 0.9977]]

In [14]:
randomNumbers = np.random.rand(700)
category3 = pd.qcut(randomNumbers, 5)
print(category3)

[(0.424, 0.602], (0.424, 0.602], (0.00164, 0.2], (0.00164, 0.2], (0.602, 0.807], ..., (0.602, 0.807], (0.602, 0.807], (0.00164, 0.2], (0.424, 0.602], (0.424, 0.602]]
Length: 700
Categories (5, interval[float64, right]): [(0.00164, 0.2] < (0.2, 0.424] < (0.424, 0.602] <
                                           (0.602, 0.807] < (0.807, 0.999]]

In [15]:
pd.value_counts(category3)

/tmp/ipykernel_589/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(0.00164, 0.2]    140
(0.2, 0.424]      140
(0.424, 0.602]    140
(0.602, 0.807]    140
(0.807, 0.999]    140
Name: count, dtype: int64

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/police_killings.csv',encoding='latin1')
df.head(10)

,name,age,gender,raceethnicity,month,day,year,streetaddress,city,state,...,share_hispanic,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,LA,...,0.5,14678,27972.0,40930,0.683411,2.0,1.0,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,WI,...,16.8,25286,45365.0,54930,0.825869,2.0,3.0,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,CA,...,98.8,17194,48295.0,55909,0.863814,3.0,3.0,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,OH,...,1.7,33954,68785.0,49669,1.384868,5.0,4.0,1.9,0.063550,0.403954
5,Adam Reinhart,29,Male,White,March,7,2015,18th St and Palm Ln,Phoenix,AZ,...,79,15523,20833.0,53596,0.388704,1.0,1.0,58,0.073651,0.102955
6,Adrian Hernandez,22,Male,Hispanic/Latino,March,27,2015,4000 Union Ave,Bakersfield,CA,...,44.2,25949,58068.0,48552,1.195996,4.0,4.0,17.2,0.131461,0.203801
7,Adrian Solis,35,Male,Hispanic/Latino,March,26,2015,1500 Bayview Ave,Wilmington,CA,...,84.1,25043,66543.0,55909,1.190202,4.0,4.0,12.2,0.094347,0.090438
8,Alan Alverson,44,Male,White,January,28,2015,Pickett Runn Rd,Sunset,TX,...,66.3,16778,30391.0,38310,0.793292,2.0,1.0,37.7,0.140833,0.047601
9,Alan James,31,Male,White,February,7,2015,200 Abbie St SE,Wyoming,MI,...,26.5,22005,44553.0,51667,0.862311,3.0,2.0,18.4,0.174167,0.102692

In [17]:
df['age']=pd.to_numeric(df['age'],errors='coerce')
TeenageCase=df[df['age']<20]
TeenageCase

,name,age,gender,raceethnicity,month,day,year,streetaddress,city,state,...,share_hispanic,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college
0,A'donte Washington,16.0,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
43,Austin Goodner,18.0,Male,White,May,17,2015,5236 Robin Ln N,St Petersburg,FL,...,5.5,26667,46233.0,45535,1.015329,3.0,3.0,17.1,0.115462,0.205355
53,Brandon Jones,18.0,Male,Black,March,19,2015,1077 Parkwood Dr,Cleveland,OH,...,0.1,14560,19643.0,43804,0.448429,1.0,1.0,32.8,0.204280,0.083227
105,David Gaines,17.0,Male,White,May,19,2015,N 10th St and Gunnison Ave,Grand Junction,CO,...,20.3,21109,30484.0,49471,0.616199,1.0,1.0,25.7,0.079277,0.261889
108,David Johnson,18.0,Male,White,May,7,2015,300 Stone Monument Dr,Wake Forest,NC,...,1.4,30061,57174.0,66006,0.866194,2.0,4.0,8.5,0.038599,0.526623
128,Deven Guilford,17.0,Male,White,March,1,2015,331 W Grand Ledge Hwy,Roxand Township,MI,...,3.1,32088,67756.0,54115,1.252074,5.0,4.0,8.5,0.090426,0.168077
143,Ebin Proctor,19.0,Male,Unknown,May,30,2015,Yuma Circle,Cottonwood,AZ,...,30.3,16415,36818.0,42987,0.856491,1.0,2.0,21.7,0.216194,0.139521
183,Hector Morejon,19.0,Male,Hispanic/Latino,April,23,2015,1100 Hoffman Ave,Long Beach,CA,...,68.2,17223,30398.0,55909,0.543705,1.0,1.0,42,0.171334,0.039808
190,Isaac Holmes,19.0,Male,Black,January,21,2015,4200 St Louis Ave,St Louis,MO,...,0,14048,18828.0,34582,0.544445,1.0,1.0,37.6,0.507614,0.029234
193,Jacob Haglund,17.0,Male,White,February,2,2015,1600 3rd St,Bay City,MI,...,19.9,14504,19097.0,45376,0.420861,1.0,1.0,40,0.260664,0.101299
215,Jason Hendrix,16.0,Male,White,February,14,2015,1486 Hyde Park Rd,Essex,MD,...,3.2,25865,38879.0,66486,0.584770,1.0,2.0,11.3,0.115929,0.136934
221,Jeffery Kemp,18.0,Male,Black,April,17,2015,74th Street and Merrill Ave,Chicago,IL,...,0.7,26314,34771.0,54548,0.637439,2.0,2.0,24.9,0.191593,0.281648
233,Jessica Hernandez,17.0,Female,Hispanic/Latino,January,26,2015,Newport St & E 25th Ave,Denver,CO,...,13.7,32602,54261.0,50313,1.078469,3.0,3.0,11.8,0.096315,0.441002
272,Justus Howell,17.0,Male,Black,April,4,2015,2300 Gilead Ave,Zion,IL,...,26.2,21955,47723.0,77469,0.616027,1.0,3.0,19.1,0.273263,0.101004
279,Kendre Alston,16.0,Male,Black,March,19,2015,1800 Helena St,Jacksonville,FL,...,0.7,14754,23880.0,48323,0.494175,1.0,1.0,36.4,0.232041,0.105286
280,Kenneth Brown,18.0,Male,White,January,4,2015,NaN,Guthrie,OK,...,6.4,16463,41901.0,53591,0.781866,2.0,2.0,33.3,0.105769,0.105675
289,Kristiana Coignard,17.0,Female,White,January,22,2015,"Longview Police Department, 302 W Cotton St",Longview,TX,...,19.7,14332,26458.0,45525,0.581175,1.0,1.0,27.4,0.137067,0.174307
290,Kyle Baker,18.0,Male,White,May,28,2015,2800 Longmeadow Dr,Trenton,MI,...,5.7,26583,60795.0,41184,1.476180,5.0,4.0,6,0.091409,0.236224
329,Michael Kocher Jr,19.0,Male,White,January,3,2015,2600 Kaumualii Hwy,Kaumakani,HI,...,11.1,30533,72000.0,62052,1.160317,5.0,4.0,5.4,0.045591,0.182048
390,Roberto Ornelas,18.0,Male,Hispanic/Latino,January,1,2015,39 N Marlin Ave,Key Largo,FL,...,21.7,25977,54219.0,53607,1.011416,3.0,3.0,16.4,0.081263,0.313959
443,Tony Robinson,19.0,Male,Black,March,6,2015,1125 Williamson St,Madison,WI,...,5.5,35028,53089.0,61721,0.860145,2.0,3.0,13.3,0.055255,0.744900
462,William Chapman II,18.0,Male,Black,April,22,2015,1098 Frederick Blvd,Portsmouth,VA,...,0,25262,27418.0,46166,0.593900,1.0,1.0,35.2,0.152047,0.120553

In [18]:
TeenageCase[['name','age','raceethnicity','cause','armed','city']]

,name,age,raceethnicity,cause,armed,city
0,A'donte Washington,16.0,Black,Gunshot,No,Millbrook
43,Austin Goodner,18.0,White,Gunshot,Firearm,St Petersburg
53,Brandon Jones,18.0,Black,Gunshot,Firearm,Cleveland
105,David Gaines,17.0,White,Gunshot,Firearm,Grand Junction
108,David Johnson,18.0,White,Gunshot,No,Wake Forest
128,Deven Guilford,17.0,White,Gunshot,Non-lethal firearm,Roxand Township
143,Ebin Proctor,19.0,Unknown,Gunshot,No,Cottonwood
183,Hector Morejon,19.0,Hispanic/Latino,Gunshot,No,Long Beach
190,Isaac Holmes,19.0,Black,Gunshot,Firearm,St Louis
193,Jacob Haglund,17.0,White,Gunshot,Knife,Bay City
215,Jason Hendrix,16.0,White,Gunshot,Firearm,Essex
221,Jeffery Kemp,18.0,Black,Gunshot,No,Chicago
233,Jessica Hernandez,17.0,Hispanic/Latino,Gunshot,Firearm,Denver
272,Justus Howell,17.0,Black,Gunshot,Firearm,Zion
279,Kendre Alston,16.0,Black,Gunshot,Firearm,Jacksonville
280,Kenneth Brown,18.0,White,Gunshot,Non-lethal firearm,Guthrie
289,Kristiana Coignard,17.0,White,Gunshot,Firearm,Longview
290,Kyle Baker,18.0,White,Gunshot,No,Trenton
329,Michael Kocher Jr,19.0,White,Struck by vehicle,Knife,Kaumakani
390,Roberto Ornelas,18.0,Hispanic/Latino,Unknown,Knife,Key Largo
443,Tony Robinson,19.0,Black,Gunshot,Firearm,Madison
462,William Chapman II,18.0,Black,Gunshot,No,Portsmouth

In [19]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
#Creating a dummy dataset with an outlier
#here we have the outlier data as 120000 in the salary column
data = {
 'Age': [25, 30, 45, 35, 22],
 'Salary': [50000, 64000, 120000, 85000, 1200000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df, "\n")
#Min-Max Scaling(Normalization)
#Rescaling generally from 0 to 1
min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
print("Min-Max Scaled Data:\n", df_min_max, "\n")
#Z-score Standardization
#we get the mean as 0 and std dev as 1 here
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
 standard_scaler.fit_transform(df),
 columns=df.columns
)
print("Standardized Data:\n", df_standard, "\n")

Original Data:
    Age   Salary
0   25    50000
1   30    64000
2   45   120000
3   35    85000
4   22  1200000

Min-Max Scaled Data:
         Age    Salary
0  0.130435  0.000000
1  0.347826  0.012174
2  1.000000  0.060870
3  0.565217  0.030435
4  0.000000  1.000000

Standardized Data:
         Age    Salary
0 -0.788742 -0.565609
1 -0.172537 -0.534409
2  1.676077 -0.409609
3  0.443667 -0.487609
4 -1.158465  1.997236